"""
Revenue Module

Calculates revenue from products and avoided disposal costs.
"""

from typing import List, Dict


class RevenueCalculator:
    """Calculates income generated by a pathway."""
    
    def __init__(self, unit_prices: Dict[str, float]):
        self.unit_prices = unit_prices
    
    def calculate_product_revenue(self, products: List[Dict]) -> float:
        """
        Calculate revenue from main products.
        
        Args:
            products: List of dicts with 'name', 'quantity', 'unit', 'price'
        """
        total = 0.0
        for item in products:
            price = item.get("price", self.unit_prices.get(item["name"], 0.0))
            total += item["quantity"] * price
        return total
    
    def calculate_avoided_cost(self, disposal_cost: float) -> float:
        """Revenue equivalent from not paying for disposal."""
        return disposal_cost


if __name__ == "__main__":
    prices = {"Cement": 0.05, "Rare Earth": 50.0}
    calc = RevenueCalculator(prices)
    rev = calc.calculate_product_revenue([{"name": "Cement", "quantity": 1000, "unit": "kg"}])
    print(f"Revenue: ${rev}")
